---
title: "final_project_p8106"
author: "Michelle Lui"
date: "4/27/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(NHANES)
library(tidyverse)
library(ggplot2) 
library(caret)
library(AppliedPredictiveModeling)
library(pROC)
library(randomForest) 
library(corrplot)
```

## Import dataset

```{r}
#import dataset
data("NHANES")

#clean dataset - limit to 2011/12 and only include biological predictors, dropped some biological predictors due to excess missing data
nhanes = NHANES %>% janitor::clean_names() %>% filter(survey_yr == "2011_12") %>% select(gender, age, race1, weight, height, bmi, pulse:bp_dia3, direct_chol:urine_flow1, diabetes) %>% drop_na()
```

# Exploratory Data Analysis
```{r}
nhanes_2 = 
  nhanes %>%
  select(diabetes, everything())

summary(nhanes_2) 

#correlation plots for predictor variables
corrx = model.matrix(diabetes~., nhanes_2)[,-1]
corrplot(cor(corrx))

#remove variables with correlation greater than 0.8
indexesToDrop = findCorrelation(cor(corrx), cutoff = 0.8)
corrplot(cor(corrx[,-indexesToDrop]))


#final dataset for analysis using RF and analysis
nhanes_3 = 
  nhanes_2 %>%
  select(diabetes, age, height, bmi, pulse, bp_sys1, bp_dia3, direct_chol, tot_chol,
         urine_vol1, urine_flow1, gender, race1)


# look at feature plots for continuous predictors (everything but race1 and gender)
theme1 = transparentTheme(trans =.4)
trellis.par.set(theme1)


featurePlot(x=nhanes_3[,2:11],
            y=nhanes_3$diabetes,
            scales =list(x=list(relation ="free"),
                         y=list(relation ="free")),
            plot ="density",pch ="|",
            auto.key =list(columns =2))
```


## Create Data Partition

```{r}
set.seed(2)

train_rows = createDataPartition(y = nhanes_3$diabetes,p = 0.7,list = FALSE)
train = nhanes_3[train_rows, ]
test = nhanes_3[-train_rows, ]

x = model.matrix(diabetes ~ ., train)[ ,-1]
y = train$diabetes

x2 = model.matrix(diabetes ~ ., test)[ ,-1]
y2 = test$diabetes

control1 = trainControl(method = "cv", selectionFunction = "best", sampling = "down")
```

## Lasso Model
```{r}
set.seed(2)
lasso_fit = train(x, y, 
                   method = "glmnet",
                   tuneGrid = expand.grid(alpha = 1, lambda = exp(seq(-20, 20,length=100))),
                   trControl = control1,
                   preProcess=c("center", "scale"),
                   family = "binomial") 

#Print the values of alpha and lambda that gave best prediction
lasso_fit$bestTune

#Print all of the options examined
lasso_fit$results

# Model coefficients
coef(lasso_fit$finalModel, s = lasso_fit$bestTune$lambda)


# Make predictions
lasso_pred = lasso_fit %>% predict(x2) %>% as.numeric()
lasso_pred_p = ifelse(lasso_pred-1 > 0.5,1,0)

test_outcome_lasso = (as.numeric(y2)-1)

misclasserror_lasso = mean(lasso_pred_p != test_outcome_lasso, na.rm=T)
print(paste('Accuracy Model 1', 1-misclasserror_lasso))

```

## Random Forest
```{r}
mtry_vals = c(ncol(train)-1, sqrt(ncol(train)-1), 0.5*ncol(train)-1)

mtry_grid = expand.grid(.mtry=mtry_vals)

set.seed(2)
rf_fit = train(diabetes ~., 
               data = train, 
               method="rf", 
               trControl = control1, 
               metric="Accuracy", 
               tuneGrid=mtry_grid, 
               ntree=100)

rf_fit$results
rf_fit$bestTune
rf_fit$finalModel

varImp(rf_fit)
plot(varImp(rf_fit))

varImpPlot(rf_fit$finalModel)

rf_pred = predict(rf_fit, test) %>% as.numeric()
rf_pred_p = ifelse(rf_pred-1 > 0.5,1,0)

test_outcome_rf = (as.numeric(test$diabetes)-1)

misclasserror_rf = mean(rf_pred_p != test_outcome_rf, na.rm=T)
print(paste('Accuracy Model 2', 1-misclasserror_rf))

```

## Model Comparisons
```{r}
resamp = resamples(list(lasso = lasso_fit, rf = rf_fit)) 
summary(resamp)
```
## Final dataset after selecting variables from RF model
We selected variables from our random forest model since it had the highest accuracy compared to the lasso model
```{r}
#Final dataset after variable selection
nhanes_4 = 
  nhanes_3 %>%
  select(diabetes, age, bmi, bp_sys1, direct_chol, urine_flow1, height, bp_dia3, pulse, urine_vol1,
         tot_chol)
```

